# Generated by Django 5.2.8 on 2025-11-11 18:11

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoAcompanhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome do Método')),
            ],
            options={
                'verbose_name': 'Método de Acompanhamento',
                'verbose_name_plural': 'Métodos de Acompanhamento',
            },
        ),
        migrations.CreateModel(
            name='Neurodivergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=10, unique=True, verbose_name='Sigla')),
                ('nome_completo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Completo')),
            ],
            options={
                'verbose_name': 'Neurodivergência',
                'verbose_name_plural': 'Neurodivergências',
            },
        ),
        migrations.CreateModel(
            name='HistoricalPlanoTerapeutico',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('grau_neurodivergencia', models.CharField(max_length=500, verbose_name='Grau da Neurodivergência')),
                ('objetivos_tratamento', models.TextField(max_length=2000, verbose_name='Objetivos do Tratamento')),
                ('abordagem_familia', models.TextField(max_length=2000, verbose_name='Abordagem à Família')),
                ('cronograma_atividades', models.TextField(max_length=2000, verbose_name='Cronograma de Atividades')),
                ('mensagem_plano', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Mensagem Adicional')),
                ('data_criacao', models.DateTimeField(blank=True, editable=False, verbose_name='Data de Criação')),
                ('data_assinatura_terapeuta', models.DateTimeField(blank=True, null=True, verbose_name='Data Assinatura Terapeuta')),
                ('data_assinatura_familia', models.DateTimeField(blank=True, null=True, verbose_name='Data Assinatura Família')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('familiar', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contas.familiar')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('terapeuta', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contas.terapeuta')),
            ],
            options={
                'verbose_name': 'historical Plano Terapêutico',
                'verbose_name_plural': 'historical Planos Terapêuticos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PlanoMetodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planos.metodoacompanhamento')),
            ],
        ),
        migrations.CreateModel(
            name='PlanoNeurodivergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neurodivergencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planos.neurodivergencia')),
            ],
        ),
        migrations.CreateModel(
            name='PlanoTerapeutico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grau_neurodivergencia', models.CharField(max_length=500, verbose_name='Grau da Neurodivergência')),
                ('objetivos_tratamento', models.TextField(max_length=2000, verbose_name='Objetivos do Tratamento')),
                ('abordagem_familia', models.TextField(max_length=2000, verbose_name='Abordagem à Família')),
                ('cronograma_atividades', models.TextField(max_length=2000, verbose_name='Cronograma de Atividades')),
                ('mensagem_plano', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Mensagem Adicional')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_assinatura_terapeuta', models.DateTimeField(blank=True, null=True, verbose_name='Data Assinatura Terapeuta')),
                ('data_assinatura_familia', models.DateTimeField(blank=True, null=True, verbose_name='Data Assinatura Família')),
                ('familiar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_associados', to='contas.familiar')),
                ('metodos', models.ManyToManyField(related_name='planos_aplicados', through='planos.PlanoMetodo', to='planos.metodoacompanhamento')),
                ('neurodivergencias', models.ManyToManyField(related_name='planos_relacionados', through='planos.PlanoNeurodivergencia', to='planos.neurodivergencia')),
                ('terapeuta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planos_criados', to='contas.terapeuta')),
            ],
            options={
                'verbose_name': 'Plano Terapêutico',
                'verbose_name_plural': 'Planos Terapêuticos',
            },
        ),
        migrations.AddField(
            model_name='planoneurodivergencia',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planos.planoterapeutico'),
        ),
        migrations.AddField(
            model_name='planometodo',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planos.planoterapeutico'),
        ),
        migrations.CreateModel(
            name='AnexoPlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='planos/anexos/')),
                ('nome_arquivo', models.CharField(max_length=255, verbose_name='Nome do Arquivo')),
                ('tipo_mime', models.CharField(max_length=100, verbose_name='Tipo MIME')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='planos.planoterapeutico')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='planoneurodivergencia',
            unique_together={('plano', 'neurodivergencia')},
        ),
        migrations.AlterUniqueTogether(
            name='planometodo',
            unique_together={('plano', 'metodo')},
        ),
    ]
