# Generated by Django 5.2.6 on 2025-10-21 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiarioCompartilhado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField()),
                ('imagens', models.BinaryField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=12)),
                ('cpf', models.CharField(max_length=11, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=11, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Terapeuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=12)),
                ('crp', models.CharField(max_length=7, unique=True)),
                ('especialidade', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('consentimento_lgpd', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField()),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.diariocompartilhado')),
                ('terapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.terapeuta')),
            ],
        ),
        migrations.CreateModel(
            name='FamiliarPlanoTerapeuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familiar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.familiar')),
            ],
        ),
        migrations.CreateModel(
            name='Observacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_observacao', models.CharField(max_length=255)),
                ('data_envio', models.DateField()),
                ('data_edicao', models.DateField(blank=True, null=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.checklist')),
                ('familiar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.familiar')),
            ],
        ),
        migrations.CreateModel(
            name='Neurodivergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255)),
                ('grau', models.IntegerField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
            ],
        ),
        migrations.AddField(
            model_name='diariocompartilhado',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente'),
        ),
        migrations.CreateModel(
            name='PlanoTerapeuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField()),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('arquivo', models.BinaryField(blank=True, null=True)),
                ('data_modificacao', models.DateField(blank=True, null=True)),
                ('descricao_plano', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField()),
                ('familiares', models.ManyToManyField(through='core.FamiliarPlanoTerapeuta', to='core.familiar')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
                ('terapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.terapeuta')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoPlanoTerapeuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_fim', models.DateField()),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.planoterapeuta')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_feedback', models.CharField(max_length=255)),
                ('resposta_terapeuta', models.CharField(blank=True, max_length=255, null=True)),
                ('data_envio', models.DateField()),
                ('familiar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.familiar')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.planoterapeuta')),
            ],
        ),
        migrations.AddField(
            model_name='familiarplanoterapeuta',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.planoterapeuta'),
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.BinaryField()),
                ('familiar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.familiar')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
                ('terapeuta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.terapeuta')),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_mensagem', models.CharField(max_length=500)),
                ('data_envio', models.DateField()),
                ('data_edicao', models.DateField(blank=True, null=True)),
                ('diario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.diariocompartilhado')),
                ('familiar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.familiar')),
                ('terapeuta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.terapeuta')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_sessao', models.DateField()),
                ('descricao_sessao', models.CharField(max_length=255)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.planoterapeuta')),
                ('terapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.terapeuta')),
            ],
        ),
        migrations.AddField(
            model_name='terapeuta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
        migrations.AddField(
            model_name='familiar',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('consentimento_lgpd', models.BooleanField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='DiarioFamiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.diariocompartilhado')),
                ('familiar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.familiar')),
            ],
            options={
                'unique_together': {('diario', 'familiar')},
            },
        ),
        migrations.CreateModel(
            name='PacienteFamiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familiar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.familiar')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
            ],
            options={
                'unique_together': {('paciente', 'familiar')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='familiarplanoterapeuta',
            unique_together={('plano', 'familiar')},
        ),
        migrations.CreateModel(
            name='PacienteTerapeuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
                ('terapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.terapeuta')),
            ],
            options={
                'unique_together': {('paciente', 'terapeuta')},
            },
        ),
        migrations.CreateModel(
            name='DiarioTerapeuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.diariocompartilhado')),
                ('terapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.terapeuta')),
            ],
            options={
                'unique_together': {('diario', 'terapeuta')},
            },
        ),
    ]
